name: Feature Request
description: You want more!
assignees: DevDyna
labels: [feature request]
body:
  - type: textarea
    id: large-text-box
    attributes:
      label: Description
      description: Describe what you want that i add on this project
      placeholder: 
    validations:
      required: true
